version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  redis:
    image: "redis:6.2.6-alpine"
    ports:
      - "6379:6379"
  db:
    image: "postgres:14.2-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Synesta17
      - POSTGRES_DB=AvitoDb

volumes:
  app_data: